Add quakedef.h include for Visual Studio precompiled header
Visual Studio requires quakedef.h to be included before other headers
for precompiled header support. This fixes the compilation error:
'unexpected end of file while looking for precompiled header'